namespace markez_ahl_alquran.PL
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnStudentPresentManagment = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnStudentProgressEntry = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnManageStudents = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnManageClasses = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnManageTeacher = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnReportsManagement = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.btnReportsManagement);
            this.bunifuPanel1.Controls.Add(this.btnStudentPresentManagment);
            this.bunifuPanel1.Controls.Add(this.btnStudentProgressEntry);
            this.bunifuPanel1.Controls.Add(this.btnManageStudents);
            this.bunifuPanel1.Controls.Add(this.btnManageClasses);
            this.bunifuPanel1.Controls.Add(this.btnManageTeacher);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(215, 794);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // btnStudentPresentManagment
            // 
            this.btnStudentPresentManagment.AllowAnimations = true;
            this.btnStudentPresentManagment.AllowMouseEffects = true;
            this.btnStudentPresentManagment.AllowToggling = false;
            this.btnStudentPresentManagment.AnimationSpeed = 200;
            this.btnStudentPresentManagment.AutoGenerateColors = false;
            this.btnStudentPresentManagment.AutoRoundBorders = false;
            this.btnStudentPresentManagment.AutoSizeLeftIcon = true;
            this.btnStudentPresentManagment.AutoSizeRightIcon = true;
            this.btnStudentPresentManagment.BackColor = System.Drawing.Color.Transparent;
            this.btnStudentPresentManagment.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnStudentPresentManagment.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnStudentPresentManagment.BackgroundImage")));
            this.btnStudentPresentManagment.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStudentPresentManagment.ButtonText = "إدارة الحضور والغياب";
            this.btnStudentPresentManagment.ButtonTextMarginLeft = 0;
            this.btnStudentPresentManagment.ColorContrastOnClick = 45;
            this.btnStudentPresentManagment.ColorContrastOnHover = 45;
            this.btnStudentPresentManagment.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnStudentPresentManagment.CustomizableEdges = borderEdges2;
            this.btnStudentPresentManagment.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnStudentPresentManagment.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnStudentPresentManagment.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnStudentPresentManagment.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnStudentPresentManagment.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnStudentPresentManagment.Font = new System.Drawing.Font("Arial", 11F);
            this.btnStudentPresentManagment.ForeColor = System.Drawing.Color.White;
            this.btnStudentPresentManagment.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnStudentPresentManagment.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnStudentPresentManagment.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnStudentPresentManagment.IconMarginLeft = 11;
            this.btnStudentPresentManagment.IconPadding = 10;
            this.btnStudentPresentManagment.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnStudentPresentManagment.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnStudentPresentManagment.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnStudentPresentManagment.IconSize = 25;
            this.btnStudentPresentManagment.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnStudentPresentManagment.IdleBorderRadius = 1;
            this.btnStudentPresentManagment.IdleBorderThickness = 1;
            this.btnStudentPresentManagment.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnStudentPresentManagment.IdleIconLeftImage = null;
            this.btnStudentPresentManagment.IdleIconRightImage = null;
            this.btnStudentPresentManagment.IndicateFocus = false;
            this.btnStudentPresentManagment.Location = new System.Drawing.Point(29, 366);
            this.btnStudentPresentManagment.Name = "btnStudentPresentManagment";
            this.btnStudentPresentManagment.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnStudentPresentManagment.OnDisabledState.BorderRadius = 1;
            this.btnStudentPresentManagment.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStudentPresentManagment.OnDisabledState.BorderThickness = 1;
            this.btnStudentPresentManagment.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnStudentPresentManagment.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnStudentPresentManagment.OnDisabledState.IconLeftImage = null;
            this.btnStudentPresentManagment.OnDisabledState.IconRightImage = null;
            this.btnStudentPresentManagment.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnStudentPresentManagment.onHoverState.BorderRadius = 1;
            this.btnStudentPresentManagment.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStudentPresentManagment.onHoverState.BorderThickness = 1;
            this.btnStudentPresentManagment.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnStudentPresentManagment.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnStudentPresentManagment.onHoverState.IconLeftImage = null;
            this.btnStudentPresentManagment.onHoverState.IconRightImage = null;
            this.btnStudentPresentManagment.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnStudentPresentManagment.OnIdleState.BorderRadius = 1;
            this.btnStudentPresentManagment.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStudentPresentManagment.OnIdleState.BorderThickness = 1;
            this.btnStudentPresentManagment.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnStudentPresentManagment.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnStudentPresentManagment.OnIdleState.IconLeftImage = null;
            this.btnStudentPresentManagment.OnIdleState.IconRightImage = null;
            this.btnStudentPresentManagment.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnStudentPresentManagment.OnPressedState.BorderRadius = 1;
            this.btnStudentPresentManagment.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStudentPresentManagment.OnPressedState.BorderThickness = 1;
            this.btnStudentPresentManagment.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnStudentPresentManagment.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnStudentPresentManagment.OnPressedState.IconLeftImage = null;
            this.btnStudentPresentManagment.OnPressedState.IconRightImage = null;
            this.btnStudentPresentManagment.Size = new System.Drawing.Size(150, 39);
            this.btnStudentPresentManagment.TabIndex = 4;
            this.btnStudentPresentManagment.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnStudentPresentManagment.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnStudentPresentManagment.TextMarginLeft = 0;
            this.btnStudentPresentManagment.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnStudentPresentManagment.UseDefaultRadiusAndThickness = true;
            this.btnStudentPresentManagment.Click += new System.EventHandler(this.btnStudentManagment);
            // 
            // btnStudentProgressEntry
            // 
            this.btnStudentProgressEntry.AllowAnimations = true;
            this.btnStudentProgressEntry.AllowMouseEffects = true;
            this.btnStudentProgressEntry.AllowToggling = false;
            this.btnStudentProgressEntry.AnimationSpeed = 200;
            this.btnStudentProgressEntry.AutoGenerateColors = false;
            this.btnStudentProgressEntry.AutoRoundBorders = false;
            this.btnStudentProgressEntry.AutoSizeLeftIcon = true;
            this.btnStudentProgressEntry.AutoSizeRightIcon = true;
            this.btnStudentProgressEntry.BackColor = System.Drawing.Color.Transparent;
            this.btnStudentProgressEntry.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnStudentProgressEntry.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnStudentProgressEntry.BackgroundImage")));
            this.btnStudentProgressEntry.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStudentProgressEntry.ButtonText = "إدارة الحفظ والمراجعة";
            this.btnStudentProgressEntry.ButtonTextMarginLeft = 0;
            this.btnStudentProgressEntry.ColorContrastOnClick = 45;
            this.btnStudentProgressEntry.ColorContrastOnHover = 45;
            this.btnStudentProgressEntry.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnStudentProgressEntry.CustomizableEdges = borderEdges3;
            this.btnStudentProgressEntry.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnStudentProgressEntry.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnStudentProgressEntry.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnStudentProgressEntry.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnStudentProgressEntry.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnStudentProgressEntry.Font = new System.Drawing.Font("Arial", 11F);
            this.btnStudentProgressEntry.ForeColor = System.Drawing.Color.White;
            this.btnStudentProgressEntry.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnStudentProgressEntry.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnStudentProgressEntry.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnStudentProgressEntry.IconMarginLeft = 11;
            this.btnStudentProgressEntry.IconPadding = 10;
            this.btnStudentProgressEntry.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnStudentProgressEntry.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnStudentProgressEntry.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnStudentProgressEntry.IconSize = 25;
            this.btnStudentProgressEntry.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnStudentProgressEntry.IdleBorderRadius = 1;
            this.btnStudentProgressEntry.IdleBorderThickness = 1;
            this.btnStudentProgressEntry.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnStudentProgressEntry.IdleIconLeftImage = null;
            this.btnStudentProgressEntry.IdleIconRightImage = null;
            this.btnStudentProgressEntry.IndicateFocus = false;
            this.btnStudentProgressEntry.Location = new System.Drawing.Point(29, 284);
            this.btnStudentProgressEntry.Name = "btnStudentProgressEntry";
            this.btnStudentProgressEntry.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnStudentProgressEntry.OnDisabledState.BorderRadius = 1;
            this.btnStudentProgressEntry.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStudentProgressEntry.OnDisabledState.BorderThickness = 1;
            this.btnStudentProgressEntry.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnStudentProgressEntry.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnStudentProgressEntry.OnDisabledState.IconLeftImage = null;
            this.btnStudentProgressEntry.OnDisabledState.IconRightImage = null;
            this.btnStudentProgressEntry.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnStudentProgressEntry.onHoverState.BorderRadius = 1;
            this.btnStudentProgressEntry.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStudentProgressEntry.onHoverState.BorderThickness = 1;
            this.btnStudentProgressEntry.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnStudentProgressEntry.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnStudentProgressEntry.onHoverState.IconLeftImage = null;
            this.btnStudentProgressEntry.onHoverState.IconRightImage = null;
            this.btnStudentProgressEntry.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnStudentProgressEntry.OnIdleState.BorderRadius = 1;
            this.btnStudentProgressEntry.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStudentProgressEntry.OnIdleState.BorderThickness = 1;
            this.btnStudentProgressEntry.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnStudentProgressEntry.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnStudentProgressEntry.OnIdleState.IconLeftImage = null;
            this.btnStudentProgressEntry.OnIdleState.IconRightImage = null;
            this.btnStudentProgressEntry.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnStudentProgressEntry.OnPressedState.BorderRadius = 1;
            this.btnStudentProgressEntry.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStudentProgressEntry.OnPressedState.BorderThickness = 1;
            this.btnStudentProgressEntry.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnStudentProgressEntry.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnStudentProgressEntry.OnPressedState.IconLeftImage = null;
            this.btnStudentProgressEntry.OnPressedState.IconRightImage = null;
            this.btnStudentProgressEntry.Size = new System.Drawing.Size(150, 39);
            this.btnStudentProgressEntry.TabIndex = 3;
            this.btnStudentProgressEntry.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnStudentProgressEntry.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnStudentProgressEntry.TextMarginLeft = 0;
            this.btnStudentProgressEntry.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnStudentProgressEntry.UseDefaultRadiusAndThickness = true;
            this.btnStudentProgressEntry.Click += new System.EventHandler(this.btnStudentProgressEntry_Click);
            // 
            // btnManageStudents
            // 
            this.btnManageStudents.AllowAnimations = true;
            this.btnManageStudents.AllowMouseEffects = true;
            this.btnManageStudents.AllowToggling = false;
            this.btnManageStudents.AnimationSpeed = 200;
            this.btnManageStudents.AutoGenerateColors = false;
            this.btnManageStudents.AutoRoundBorders = false;
            this.btnManageStudents.AutoSizeLeftIcon = true;
            this.btnManageStudents.AutoSizeRightIcon = true;
            this.btnManageStudents.BackColor = System.Drawing.Color.Transparent;
            this.btnManageStudents.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnManageStudents.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnManageStudents.BackgroundImage")));
            this.btnManageStudents.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageStudents.ButtonText = "إدارة الطلاب";
            this.btnManageStudents.ButtonTextMarginLeft = 0;
            this.btnManageStudents.ColorContrastOnClick = 45;
            this.btnManageStudents.ColorContrastOnHover = 45;
            this.btnManageStudents.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnManageStudents.CustomizableEdges = borderEdges4;
            this.btnManageStudents.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnManageStudents.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnManageStudents.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnManageStudents.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnManageStudents.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnManageStudents.Font = new System.Drawing.Font("Arial", 11F);
            this.btnManageStudents.ForeColor = System.Drawing.Color.White;
            this.btnManageStudents.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnManageStudents.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnManageStudents.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnManageStudents.IconMarginLeft = 11;
            this.btnManageStudents.IconPadding = 10;
            this.btnManageStudents.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnManageStudents.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnManageStudents.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnManageStudents.IconSize = 25;
            this.btnManageStudents.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnManageStudents.IdleBorderRadius = 1;
            this.btnManageStudents.IdleBorderThickness = 1;
            this.btnManageStudents.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnManageStudents.IdleIconLeftImage = null;
            this.btnManageStudents.IdleIconRightImage = null;
            this.btnManageStudents.IndicateFocus = false;
            this.btnManageStudents.Location = new System.Drawing.Point(29, 205);
            this.btnManageStudents.Name = "btnManageStudents";
            this.btnManageStudents.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnManageStudents.OnDisabledState.BorderRadius = 1;
            this.btnManageStudents.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageStudents.OnDisabledState.BorderThickness = 1;
            this.btnManageStudents.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnManageStudents.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnManageStudents.OnDisabledState.IconLeftImage = null;
            this.btnManageStudents.OnDisabledState.IconRightImage = null;
            this.btnManageStudents.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnManageStudents.onHoverState.BorderRadius = 1;
            this.btnManageStudents.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageStudents.onHoverState.BorderThickness = 1;
            this.btnManageStudents.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnManageStudents.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnManageStudents.onHoverState.IconLeftImage = null;
            this.btnManageStudents.onHoverState.IconRightImage = null;
            this.btnManageStudents.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnManageStudents.OnIdleState.BorderRadius = 1;
            this.btnManageStudents.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageStudents.OnIdleState.BorderThickness = 1;
            this.btnManageStudents.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnManageStudents.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnManageStudents.OnIdleState.IconLeftImage = null;
            this.btnManageStudents.OnIdleState.IconRightImage = null;
            this.btnManageStudents.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnManageStudents.OnPressedState.BorderRadius = 1;
            this.btnManageStudents.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageStudents.OnPressedState.BorderThickness = 1;
            this.btnManageStudents.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnManageStudents.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnManageStudents.OnPressedState.IconLeftImage = null;
            this.btnManageStudents.OnPressedState.IconRightImage = null;
            this.btnManageStudents.Size = new System.Drawing.Size(150, 39);
            this.btnManageStudents.TabIndex = 2;
            this.btnManageStudents.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnManageStudents.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnManageStudents.TextMarginLeft = 0;
            this.btnManageStudents.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnManageStudents.UseDefaultRadiusAndThickness = true;
            this.btnManageStudents.Click += new System.EventHandler(this.btnManageStudents_Click);
            // 
            // btnManageClasses
            // 
            this.btnManageClasses.AllowAnimations = true;
            this.btnManageClasses.AllowMouseEffects = true;
            this.btnManageClasses.AllowToggling = false;
            this.btnManageClasses.AnimationSpeed = 200;
            this.btnManageClasses.AutoGenerateColors = false;
            this.btnManageClasses.AutoRoundBorders = false;
            this.btnManageClasses.AutoSizeLeftIcon = true;
            this.btnManageClasses.AutoSizeRightIcon = true;
            this.btnManageClasses.BackColor = System.Drawing.Color.Transparent;
            this.btnManageClasses.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnManageClasses.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnManageClasses.BackgroundImage")));
            this.btnManageClasses.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageClasses.ButtonText = "إدارة الحلقات";
            this.btnManageClasses.ButtonTextMarginLeft = 0;
            this.btnManageClasses.ColorContrastOnClick = 45;
            this.btnManageClasses.ColorContrastOnHover = 45;
            this.btnManageClasses.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnManageClasses.CustomizableEdges = borderEdges5;
            this.btnManageClasses.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnManageClasses.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnManageClasses.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnManageClasses.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnManageClasses.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnManageClasses.Font = new System.Drawing.Font("Arial", 11F);
            this.btnManageClasses.ForeColor = System.Drawing.Color.White;
            this.btnManageClasses.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnManageClasses.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnManageClasses.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnManageClasses.IconMarginLeft = 11;
            this.btnManageClasses.IconPadding = 10;
            this.btnManageClasses.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnManageClasses.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnManageClasses.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnManageClasses.IconSize = 25;
            this.btnManageClasses.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnManageClasses.IdleBorderRadius = 1;
            this.btnManageClasses.IdleBorderThickness = 1;
            this.btnManageClasses.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnManageClasses.IdleIconLeftImage = null;
            this.btnManageClasses.IdleIconRightImage = null;
            this.btnManageClasses.IndicateFocus = false;
            this.btnManageClasses.Location = new System.Drawing.Point(29, 122);
            this.btnManageClasses.Name = "btnManageClasses";
            this.btnManageClasses.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnManageClasses.OnDisabledState.BorderRadius = 1;
            this.btnManageClasses.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageClasses.OnDisabledState.BorderThickness = 1;
            this.btnManageClasses.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnManageClasses.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnManageClasses.OnDisabledState.IconLeftImage = null;
            this.btnManageClasses.OnDisabledState.IconRightImage = null;
            this.btnManageClasses.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnManageClasses.onHoverState.BorderRadius = 1;
            this.btnManageClasses.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageClasses.onHoverState.BorderThickness = 1;
            this.btnManageClasses.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnManageClasses.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnManageClasses.onHoverState.IconLeftImage = null;
            this.btnManageClasses.onHoverState.IconRightImage = null;
            this.btnManageClasses.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnManageClasses.OnIdleState.BorderRadius = 1;
            this.btnManageClasses.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageClasses.OnIdleState.BorderThickness = 1;
            this.btnManageClasses.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnManageClasses.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnManageClasses.OnIdleState.IconLeftImage = null;
            this.btnManageClasses.OnIdleState.IconRightImage = null;
            this.btnManageClasses.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnManageClasses.OnPressedState.BorderRadius = 1;
            this.btnManageClasses.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageClasses.OnPressedState.BorderThickness = 1;
            this.btnManageClasses.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnManageClasses.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnManageClasses.OnPressedState.IconLeftImage = null;
            this.btnManageClasses.OnPressedState.IconRightImage = null;
            this.btnManageClasses.Size = new System.Drawing.Size(150, 39);
            this.btnManageClasses.TabIndex = 1;
            this.btnManageClasses.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnManageClasses.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnManageClasses.TextMarginLeft = 0;
            this.btnManageClasses.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnManageClasses.UseDefaultRadiusAndThickness = true;
            this.btnManageClasses.Click += new System.EventHandler(this.btnManageClasses_Click);
            // 
            // btnManageTeacher
            // 
            this.btnManageTeacher.AllowAnimations = true;
            this.btnManageTeacher.AllowMouseEffects = true;
            this.btnManageTeacher.AllowToggling = false;
            this.btnManageTeacher.AnimationSpeed = 200;
            this.btnManageTeacher.AutoGenerateColors = false;
            this.btnManageTeacher.AutoRoundBorders = false;
            this.btnManageTeacher.AutoSizeLeftIcon = true;
            this.btnManageTeacher.AutoSizeRightIcon = true;
            this.btnManageTeacher.BackColor = System.Drawing.Color.Transparent;
            this.btnManageTeacher.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnManageTeacher.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnManageTeacher.BackgroundImage")));
            this.btnManageTeacher.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageTeacher.ButtonText = "إدارة المعلمين";
            this.btnManageTeacher.ButtonTextMarginLeft = 0;
            this.btnManageTeacher.ColorContrastOnClick = 45;
            this.btnManageTeacher.ColorContrastOnHover = 45;
            this.btnManageTeacher.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnManageTeacher.CustomizableEdges = borderEdges6;
            this.btnManageTeacher.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnManageTeacher.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnManageTeacher.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnManageTeacher.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnManageTeacher.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnManageTeacher.Font = new System.Drawing.Font("Arial", 11F);
            this.btnManageTeacher.ForeColor = System.Drawing.Color.White;
            this.btnManageTeacher.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnManageTeacher.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnManageTeacher.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnManageTeacher.IconMarginLeft = 11;
            this.btnManageTeacher.IconPadding = 10;
            this.btnManageTeacher.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnManageTeacher.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnManageTeacher.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnManageTeacher.IconSize = 25;
            this.btnManageTeacher.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnManageTeacher.IdleBorderRadius = 1;
            this.btnManageTeacher.IdleBorderThickness = 1;
            this.btnManageTeacher.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnManageTeacher.IdleIconLeftImage = null;
            this.btnManageTeacher.IdleIconRightImage = null;
            this.btnManageTeacher.IndicateFocus = false;
            this.btnManageTeacher.Location = new System.Drawing.Point(29, 40);
            this.btnManageTeacher.Name = "btnManageTeacher";
            this.btnManageTeacher.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnManageTeacher.OnDisabledState.BorderRadius = 1;
            this.btnManageTeacher.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageTeacher.OnDisabledState.BorderThickness = 1;
            this.btnManageTeacher.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnManageTeacher.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnManageTeacher.OnDisabledState.IconLeftImage = null;
            this.btnManageTeacher.OnDisabledState.IconRightImage = null;
            this.btnManageTeacher.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnManageTeacher.onHoverState.BorderRadius = 1;
            this.btnManageTeacher.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageTeacher.onHoverState.BorderThickness = 1;
            this.btnManageTeacher.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnManageTeacher.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnManageTeacher.onHoverState.IconLeftImage = null;
            this.btnManageTeacher.onHoverState.IconRightImage = null;
            this.btnManageTeacher.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnManageTeacher.OnIdleState.BorderRadius = 1;
            this.btnManageTeacher.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageTeacher.OnIdleState.BorderThickness = 1;
            this.btnManageTeacher.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnManageTeacher.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnManageTeacher.OnIdleState.IconLeftImage = null;
            this.btnManageTeacher.OnIdleState.IconRightImage = null;
            this.btnManageTeacher.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnManageTeacher.OnPressedState.BorderRadius = 1;
            this.btnManageTeacher.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageTeacher.OnPressedState.BorderThickness = 1;
            this.btnManageTeacher.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnManageTeacher.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnManageTeacher.OnPressedState.IconLeftImage = null;
            this.btnManageTeacher.OnPressedState.IconRightImage = null;
            this.btnManageTeacher.Size = new System.Drawing.Size(150, 39);
            this.btnManageTeacher.TabIndex = 0;
            this.btnManageTeacher.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnManageTeacher.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnManageTeacher.TextMarginLeft = 0;
            this.btnManageTeacher.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnManageTeacher.UseDefaultRadiusAndThickness = true;
            this.btnManageTeacher.Click += new System.EventHandler(this.btnManageTeacher_Click);
            // 
            // btnReportsManagement
            // 
            this.btnReportsManagement.AllowAnimations = true;
            this.btnReportsManagement.AllowMouseEffects = true;
            this.btnReportsManagement.AllowToggling = false;
            this.btnReportsManagement.AnimationSpeed = 200;
            this.btnReportsManagement.AutoGenerateColors = false;
            this.btnReportsManagement.AutoRoundBorders = false;
            this.btnReportsManagement.AutoSizeLeftIcon = true;
            this.btnReportsManagement.AutoSizeRightIcon = true;
            this.btnReportsManagement.BackColor = System.Drawing.Color.Transparent;
            this.btnReportsManagement.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnReportsManagement.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnReportsManagement.BackgroundImage")));
            this.btnReportsManagement.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnReportsManagement.ButtonText = "إدارة التقارير";
            this.btnReportsManagement.ButtonTextMarginLeft = 0;
            this.btnReportsManagement.ColorContrastOnClick = 45;
            this.btnReportsManagement.ColorContrastOnHover = 45;
            this.btnReportsManagement.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnReportsManagement.CustomizableEdges = borderEdges1;
            this.btnReportsManagement.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnReportsManagement.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnReportsManagement.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnReportsManagement.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnReportsManagement.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnReportsManagement.Font = new System.Drawing.Font("Arial", 11F);
            this.btnReportsManagement.ForeColor = System.Drawing.Color.White;
            this.btnReportsManagement.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnReportsManagement.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnReportsManagement.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnReportsManagement.IconMarginLeft = 11;
            this.btnReportsManagement.IconPadding = 10;
            this.btnReportsManagement.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnReportsManagement.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnReportsManagement.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnReportsManagement.IconSize = 25;
            this.btnReportsManagement.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnReportsManagement.IdleBorderRadius = 1;
            this.btnReportsManagement.IdleBorderThickness = 1;
            this.btnReportsManagement.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnReportsManagement.IdleIconLeftImage = null;
            this.btnReportsManagement.IdleIconRightImage = null;
            this.btnReportsManagement.IndicateFocus = false;
            this.btnReportsManagement.Location = new System.Drawing.Point(29, 437);
            this.btnReportsManagement.Name = "btnReportsManagement";
            this.btnReportsManagement.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnReportsManagement.OnDisabledState.BorderRadius = 1;
            this.btnReportsManagement.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnReportsManagement.OnDisabledState.BorderThickness = 1;
            this.btnReportsManagement.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnReportsManagement.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnReportsManagement.OnDisabledState.IconLeftImage = null;
            this.btnReportsManagement.OnDisabledState.IconRightImage = null;
            this.btnReportsManagement.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnReportsManagement.onHoverState.BorderRadius = 1;
            this.btnReportsManagement.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnReportsManagement.onHoverState.BorderThickness = 1;
            this.btnReportsManagement.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnReportsManagement.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnReportsManagement.onHoverState.IconLeftImage = null;
            this.btnReportsManagement.onHoverState.IconRightImage = null;
            this.btnReportsManagement.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnReportsManagement.OnIdleState.BorderRadius = 1;
            this.btnReportsManagement.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnReportsManagement.OnIdleState.BorderThickness = 1;
            this.btnReportsManagement.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnReportsManagement.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnReportsManagement.OnIdleState.IconLeftImage = null;
            this.btnReportsManagement.OnIdleState.IconRightImage = null;
            this.btnReportsManagement.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnReportsManagement.OnPressedState.BorderRadius = 1;
            this.btnReportsManagement.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnReportsManagement.OnPressedState.BorderThickness = 1;
            this.btnReportsManagement.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnReportsManagement.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnReportsManagement.OnPressedState.IconLeftImage = null;
            this.btnReportsManagement.OnPressedState.IconRightImage = null;
            this.btnReportsManagement.Size = new System.Drawing.Size(150, 39);
            this.btnReportsManagement.TabIndex = 5;
            this.btnReportsManagement.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnReportsManagement.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnReportsManagement.TextMarginLeft = 0;
            this.btnReportsManagement.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnReportsManagement.UseDefaultRadiusAndThickness = true;
            this.btnReportsManagement.Click += new System.EventHandler(this.btnReportsManagement_Click);
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1781, 794);
            this.Controls.Add(this.bunifuPanel1);
            this.Name = "MainForm";
            this.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.RightToLeftLayout = true;
            this.Text = "MainForm";
            this.Load += new System.EventHandler(this.MainForm_Load);
            this.bunifuPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnManageStudents;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnManageClasses;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnManageTeacher;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnStudentProgressEntry;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnStudentPresentManagment;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnReportsManagement;
    }
}